#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
          
      - name: Download lede
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git  lede
          cp 36.config ./lede/.config
          

      - name: Update feeds
        run: |
          cp -rf scripts/*.sh lede/
          cd   lede
          chmod +x  diy-script.sh
          chmod +x  preset-clash-core.sh
          ./diy-script.sh
          ./preset-clash-core.sh

          
      - name: Costom configure file
        run: |
          cd   lede
          make defconfig
          
      - name: Compile firmware
        run: |
          cd   lede
          echo -e "$(nproc) thread build."
          make -j$(nproc)
          
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: lede/bin/targets/
          
